In [2]:
import numpy as np
from numpy import ndarray
import pandas as pd
from pandas import DataFrame

scores: ndarray | None = None
scores_df: DataFrame | None = None

scores = np.random.randint(50, 101, size=(50, 5))
scores_df = pd.DataFrame(scores,
                         columns = ["國文", "數學", "英文", "地理", "歷史"],
                         index = range(1,51))
# print(scores_df.T)

names_df = pd.read_csv('students.csv')
# 如果裡面沒有姓名就會自動補上
# names_df[]外面是subscript ，裡面是list
scores_df[['姓名','性別']] = names_df[['姓名','性別']].head(50).values
scores_df.groupby('性別')[["國文", "數學", "英文", "地理", "歷史"]].agg('mean')

           國文         數學         英文         地理         歷史
性別
女   78.857143  80.047619  69.238095  73.666667  75.761905
男   73.689655  76.448276  73.172414  77.448276  75.379310

In [4]:
scores_df
# scores_df:
# 1. 要gruopby性別
# 2. 還要gruopby學生總分，且學生總紛紛為3個階級:高分區、一般區、低分區
scores_df['總分'] = scores_df[["國文", "數學", "英文", "地理", "歷史"]].sum(axis=1)
scores_df['總分階級'] = pd.cut(
    scores_df['總分'],
    bins=[0,250,350,500],
    labels=['低分區', '一般區', '高分區']
)
scores_df.groupby(['性別', '總分階級'])['總分'].agg(['count', 'mean', 'min', 'max'])

         count        mean  min  max
性別 總分階級
女  一般區       5  340.200000  335  344
   高分區      16  389.250000  356  448
男  一般區       5  317.000000  277  350
   高分區      24  388.458333  354  454